OpenSkoolSecurityBundle:
    resource: "@OpenSkoolSecurityBundle/Resources/config/routing/routing.yml"

OpenSkoolAdminBundle:
    resource: "@OpenSkoolAdminBundle/Resources/config/routing/routing.yml"
    
OpenSkoolCoreBundle:
    resource: "@OpenSkoolCoreBundle/Resources/config/routing/routing.yml"
    
OpenSkoolPeopleBundle:
    resource: "@OpenSkoolPeopleBundle/Resources/config/routing/routing.yml"
    
YepsuaLOVBundle:
    resource: "@YepsuaLOVBundle/Resources/config/routing/routing.yml"
    prefix:   /admin
    
YepsuaLocalityBundle:
    resource: "@YepsuaLocalityBundle/Resources/config/routing/routing.yml"
    prefix:   /admin
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_group_profile:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin2

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin2